apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webhook
  name: webhook
spec:
  ports:
  - name: "8443"
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: webhook
  type: ClusterIP
status:
  loadBalancer: {}
