apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: simple-webhook
  labels:
    app: simple-webhook
webhooks: 
  - name: simple-webhook.default.svc.cluster.local
    clientConfig:
      caBundle: ${CA_BUNDLE}
      service:
        name: simple-webhook
        namespace: default
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersion: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        mutate: enabled
